name: Test
on:
  push:
    # branches:
    #   - 'main'
    #   - 'develop'
    #   - 'master'
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: Install Node JS
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        run: npm test
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: Install Node version
        uses: actions/setup-node@v5
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Deploy 
        run: echo "Deployment is done"
